name: lint-and-test

on: [push, workflow_dispatch]

env:
  elixir_version_current: '1.16'
  otp_version_current: '25.3'

jobs:
  variables:
    runs-on: ubuntu-latest
    outputs:
      elixir_version_current: ${{ env.elixir_version_current }}
      otp_version_current: ${{ env.otp_version_current }}
    steps:
      - name: Output variables
        run: |
          :


  test-current:
    needs: [variables]
    strategy:
      fail-fast: false
      matrix:
        os:
          - 'ubuntu-22.04'
          - 'ubuntu-24.04'

    runs-on: ${{ matrix.os }}

    services:
      postgres:
        image: postgres:10
        env:
          POSTGRES_USER: admin
          POSTGRES_PASSWORD: admin
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - uses: actions/checkout@v4

      - uses: erlef/setup-beam@v1
        with:
          otp-version: ${{ needs.variables.outputs.otp_version_current }}
          elixir-version: ${{ needs.variables.outputs.elixir_version_current }}

      - uses: actions/cache@v4
        with:
          path: |
            deps
            _build
          key: mix-${{ hashFiles('mix.lock') }}

      - run: mix local.hex --force
      - run: mix local.rebar --force
      - run: mix deps.get
      - run: mix compile   # --warnings-as-errors
      - run: mix test


  test-matrix:
    needs: [variables]
    continue-on-error: true

    strategy:
      fail-fast: false
      matrix:
        versions:
          - elixir: '1.14'
            otp: '24.2'
          - elixir: '1.14'
            otp: '24.3'
          - elixir: '1.14'
            otp: '25.3'

          - elixir: '1.15'
            otp: '24.3'
          - elixir: '1.15'
            otp: '25.3'
          - elixir: '1.15'
            otp: '26.2'

          - elixir: '1.16'
            otp: '24.3'
          - elixir: '1.16'
            otp: '25.3'
          - elixir: '1.16'
            otp: '26.2'

          - elixir: '1.17'
            otp: '25.3'
          - elixir: '1.17'
            otp: '26.2'
          - elixir: '1.17'
            otp: '27.3'

        os:
          - 'ubuntu-22.04'
          - 'ubuntu-24.04'

        exclude:
          - versions:
              elixir: ${{ needs.variables.outputs.elixir_version_current }}
              otp: ${{ needs.variables.outputs.otp_version_current }}

          - versions:
              elixir: '1.14'
              otp: '24.2'
            os: 'ubuntu-24.04'
          - versions:
              elixir: '1.16'
              otp: '24.3'
            os: 'ubuntu-22.04'

    runs-on: ${{ matrix.os }}

    services:
      postgres:
        image: postgres:10
        env:
          POSTGRES_USER: admin
          POSTGRES_PASSWORD: admin
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - uses: actions/checkout@v4

      - uses: erlef/setup-beam@v1
        with:
          otp-version: ${{ matrix.versions.otp }}
          elixir-version: ${{ matrix.versions.elixir }}

      - uses: actions/cache@v4
        with:
          path: |
            deps
            _build
          key: mix-${{ hashFiles('mix.lock') }}

      - run: mix local.hex --force
      - run: mix local.rebar --force
      - run: mix deps.get
      - run: mix compile   # --warnings-as-errors
#        continue-on-error: ${{ matrix.versions.elixir != needs.variables.outputs.elixir_version_current || matrix.versions.otp != needs.variables.outputs.otp_version_current }}
      - run: mix test
#        continue-on-error: ${{ matrix.versions.elixir != needs.variables.outputs.elixir_version_current || matrix.versions.otp != needs.variables.outputs.otp_version_current }}


  lint:
    continue-on-error: true
    strategy:
      fail-fast: false
      matrix:
        versions:
          - elixir: '1.14'
            otp: '24.3'

          - elixir: '1.15'
            otp: '24.3'

          - elixir: '1.16'
            otp: '24.3'

          - elixir: '1.17'
            otp: '25.3'

    runs-on: 'ubuntu-24.04'

    steps:
      - uses: actions/checkout@v4

      - uses: erlef/setup-beam@v1
        with:
          otp-version: ${{ matrix.versions.otp }}
          elixir-version: ${{ matrix.versions.elixir }}

      - uses: actions/cache@v4
        with:
          path: |
            deps
            _build
          key: mix-${{ hashFiles('mix.lock') }}

#      - run: mix format '{lib,priv,test,config}/**/*.{ex,exs}'
      - run: mix format --check-formatted '{lib,priv,test,config}/**/*.{ex,exs}'
